apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - oauth2-proxy/deployment.yaml
  - oauth2-proxy/service.yaml
  - oauth2-proxy/ingress.yaml
  - oauth2-proxy/middleware.yaml
  - oauth2-proxy/errors-middleware.yaml
  - oauth2-proxy/secret.yaml
  - oauth2-proxy/reconcile-keycloak-configmap.yaml
  - oauth2-proxy/reconcile-keycloak-job.yaml
  - scan-cronjob.yaml
  - report-cronjob.yaml
