apiVersion: v1
kind: Secret
metadata:
  name: polymarket-oauth2-proxy
  namespace: polymarket-autopilot
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_SECRET: REPLACE_ME_KEYCLOAK_CLIENT_SECRET
  OAUTH2_PROXY_COOKIE_SECRET: Y8Gd4OQktDSdRQ66yibVzes_4HKPwZumdxE--IGVFk0
